name: Docker build on tag
env:
        DOCKER_CLI_EXPERIMENTAL: enabled

on:
        push:
                tags:
                  - v[0-9]+.[0-9]+.[0-9]+
                  - v[0-9]+.[0-9]+.[0-9]+-*

jobs:
        build:
                runs-on: ubuntu-18.04
                name: Build and push middleware image
                steps:
                        - name: Setup Environment
                          run: echo ::set-env name=TAG::${GITHUB_REF/refs\/tags\//} 
                                  
                        - name: Show set environment variables
                          run: |
                                  printf "    TAG: %s\n"  "$TAG"   

                        - name: Login to Docker Hub
                          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

                        - name: Checkout project
                          uses: actions/checkout@v2

                        - name: Setup Docker buildx action
                          uses: docker/setup-buildx-action@v1
                          id: buildx

                        - name: Setup QEMU
                          uses: docker/setup-qemu-action@v1
                          id: qemu

                        - name: Show available Docker buildx platforms
                          run: echo ${{ steps.buildx.outputs.platforms }}

                        - name: Cache Docker layers
                          uses: actions/cache@v2
                          id: cache
                          with:
                            path: /tmp/.buildx-cache
                            key: ${{ runner.os }}-buildx-${{ github.sha }}
                            restore-keys: |
                              ${{ runner.os }}-buildx-

                        - name: Run Docker buildx against tag
                          run: |
                                  docker buildx build \
                                  --cache-from "type=local,src=/tmp/.buildx-cache" \
                                  --cache-to "type=local,dest=/tmp/.buildx-cache" \
                                  --platform linux/amd64,linux/arm64,linux/arm/v7 \
                                  --tag ${{ secrets.DOCKER_HUB_USER }}/middleware:$TAG \
                                  --output "type=registry" ./

                        - name: Run Docker buildx against latest
                          run: |
                                  docker buildx build \
                                  --cache-from "type=local,src=/tmp/.buildx-cache" \
                                  --cache-to "type=local,dest=/tmp/.buildx-cache" \
                                  --platform linux/amd64,linux/arm64,linux/arm/v7 \
                                  --tag ${{ secrets.DOCKER_HUB_USER }}/middleware:latest \
                                  --output "type=registry" ./
